export enum userErrorCodes {
  INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_VERIFICATION_TOKEN = "INVALID_VERIFICATION_TOKEN",
  INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN",
  EXPIRED_VERIFICATION_TOKEN = "EXPIRED_VERIFICATION_TOKEN",
  EXPIRED_RESET_TOKEN = "EXPIRED_RESET_TOKEN",
  INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
}
